### ISSUE TITLE
Disabling the ArgonButtons

### ISSUE THREAD

**Issue by asnips** [iamyogik/argon_buttons_flutter#13]
I'm not sure how to go about disabling the button at the property level, or if there is even a method of doing so within the scope of ArgonTimerButton. Any advice is appreciated.

**Comment by SergeShkurko** [comment]
@iamyogik any news about it?

**Comment by SergeShkurko** [comment]
I send pull request #13

temporary solution:
```yaml
  # see https://github.com/iamyogik/argon_buttons_flutter/pull/21
  # argon_buttons_flutter: ^1.1.0
  argon_buttons_flutter:
    git: 
      url: https://github.com/SergeShkurko/argon_buttons_flutter.git
      ref: de70a781dcdafa435e16a0d91c871e9a48ccaff5
```
